name: Compilar SparkTraderBot

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache Buildozer y Gradle
        uses: actions/cache@v4
        with:
          path: |
           .buildozer
            ~/.buildozer
            ~/.gradle
          key: buildozer-${{ hashFiles('buildozer.spec') }}-v2
          restore-keys: buildozer-

      - name: Instalar dependencias sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev cmake libffi-dev libssl-dev lld libsqlite3-dev libbz2-dev libltdl-dev

      - name: Instalar Buildozer
        run: |
          pip install --upgrade pip
          pip install cython==0.29.36 buildozer

      - name: Compilar APK
        run: |
          rm -rf bin
          buildozer android debug
        env:
          # Esto acepta todas las licencias automaticamente
          P4A_ACCEPT_SDK_LICENSE_AGREEMENT: "y"

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: TraderBot-APK
          path: bin/*.apk
